#! /bin/sh

bspc rule -r "*"

xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop -f 1

###---Autostart---###
nitrogen --set-scaled --restore --head=0 &
killall cleanfullscreen
cleanfullscreen &
nm-applet &
xrdb ~/.Xresources &
picom --experimental-backends &
launchpolybar &
sxhkd &
xsetroot -cursor_name left_ptr &
dunst &
lxsession &

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/xprofile" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/xprofile"

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/SHELL/aliasrc" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/SHELL/aliasrc"

# [ -f "${HOME}/.profile" ] && source "${HOME}/.profile"
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/.profile" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/.profile"

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color "4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color   "#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 5

###---Rules---###
