#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
    bat="cat /sys/class/power_supply/BAT?/capacity" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -v" \
    mkd="mkdir -pv" \
    yt="youtube-dl --add-metadata -i" \
    ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    trem="transmission-remote" \
    sdn="sudo shutdown -h now" \
    f="$FILE" \
    e="$EDITOR" \
    v="$EDITOR" \
    p="sudo pacman"

# Git alias
alias \
    g="git" \
    gs="git status" \
    ga="git add" \
    gcmsg="git commit -m" \
    gcom="git checkout master" \
    gcod="git checkout develop" \
    glgao="git log --graph --all --oneline"

# Some other stuff
alias \
    magit="nvim -c MagitOnly" \
    tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
    irssi="irssi --config=${XDG_CONFIG_HOME}/irssi/config --home=${XDG_DATA_HOME}/irssi"
